export const PROFILE = {
  LESSOR: 1,
  TRAVELER: 2,
  PROVIDER: 3,
  MANAGEMENT: 4,
  ADMIN: 5,
};

export const ALL_PROFILES = [
  PROFILE.LESSOR,
  PROFILE.TRAVELER,
  PROFILE.PROVIDER,
  PROFILE.MANAGEMENT,
  PROFILE.ADMIN,
];

export const USER_PROFILES = [
  PROFILE.LESSOR,
  PROFILE.TRAVELER,
  PROFILE.PROVIDER,
];

export const MANAGER_PROFILES = [PROFILE.MANAGEMENT, PROFILE.ADMIN];
